package com.relief.domain.geofencing;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Represents an alert generated by geofence monitoring
 */
@Entity
@Table(name = "geofence_alerts", indexes = {
    @Index(name = "idx_geofence_alert_geofence", columnList = "geofence_id"),
    @Index(name = "idx_geofence_alert_type", columnList = "alert_type"),
    @Index(name = "idx_geofence_alert_status", columnList = "status"),
    @Index(name = "idx_geofence_alert_created_at", columnList = "created_at")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class GeofenceAlert {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "geofence_id", nullable = false)
    private Geofence geofence;
    
    @Column(name = "alert_type", nullable = false)
    @Enumerated(EnumType.STRING)
    private GeofenceAlertType alertType;
    
    @Column(name = "title", nullable = false)
    private String title;
    
    @Column(name = "message", nullable = false, columnDefinition = "TEXT")
    private String message;
    
    @Column(name = "severity", nullable = false)
    @Enumerated(EnumType.STRING)
    private GeofenceAlertSeverity severity;
    
    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.STRING)
    private GeofenceAlertStatus status;
    
    @Column(name = "triggered_by_event_id")
    private Long triggeredByEventId; // ID of the event that triggered this alert
    
    @Column(name = "alert_data", columnDefinition = "jsonb")
    private String alertData; // Additional alert data as JSON
    
    @Column(name = "notification_channels", columnDefinition = "jsonb")
    private String notificationChannels; // Channels used for notification
    
    @Column(name = "auto_actions_triggered", columnDefinition = "jsonb")
    private String autoActionsTriggered; // Automated actions that were triggered
    
    @Column(name = "assigned_to")
    private String assignedTo; // User or team assigned to handle the alert
    
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
    
    @Column(name = "acknowledged_at")
    private LocalDateTime acknowledgedAt;
    
    @Column(name = "acknowledged_by")
    private String acknowledgedBy;
    
    @Column(name = "resolved_at")
    private LocalDateTime resolvedAt;
    
    @Column(name = "resolved_by")
    private String resolvedBy;
    
    @Column(name = "resolution_notes", columnDefinition = "TEXT")
    private String resolutionNotes;
    
    @Column(name = "escalated_at")
    private LocalDateTime escalatedAt;
    
    @Column(name = "escalated_to")
    private String escalatedTo;
    
    @Column(name = "escalation_reason")
    private String escalationReason;
    
    @PrePersist
    protected void onCreate() {
        if (status == null) {
            status = GeofenceAlertStatus.ACTIVE;
        }
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}



